### ISSUE TITLE
チュートリアルドキュメント内の画像リンクが途切れている

### ISSUE THREAD

**Issue by shun-sa** [JapanExchangeGroup/J-Quants-Tutorial#30]
# 確認環境
* GoogleChrome
* MAC Safari

# 現象
以下のファイルが消えていてチュートリアル内のHTMLに画像が表示されていないように思います。
おそらくこのコミットで消えています。-> https://github.com/JapanExchangeGroup/J-Quants-Tutorial/commit/25ae67763d2207a7ac52106d818d4ec9263b46ac
HTMLの画像へのリンクを消し忘れたのか、誤って画像を消したか判断つきませんでした。
ご確認をお願いします。

```
math-sample1.svg
math-sample2.svg
simple.png
simple1.png
simple2.png
simple3.png
simple4.png
simple5.png
simple6.png
simple7.png
simple8.png
simple9.png
simple10.png
simple11.png
simple12.png
simple13.png
simple14.png
simple15.png
simple16.png
 ```

**Comment by n-onishi** [comment]
ご指摘ありがとうございます。
先週の更新の際に、いくつかの画像リンクが切れてしまっておりました。

また見つけましたらご指摘いただけますと幸いです。
どうぞよろしくお願いします。
